brew "jq"

tap "jandedobbeleer/oh-my-posh"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"

cask "font-jetbrains-mono-nerd-font"

{{ if eq .chezmoi.os "darwin" }}
  cask "rectangle"
  cask "wezterm"
{{ else if and (eq .chezmoi.os "linux") (not (contains "microsoft" (lower .chezmoi.kernel.osrelease))) }}
  tap "wezterm/wezterm-linuxbrew"
  brew "wezterm"
{{ end }}